---
services:
  influxdb:
    image: docker.io/influxdb:2.7.6
    ports:
      - 8086:8086
    volumes:
      - /home/influxdb/influxdb2:/var/lib/influxdb2
    user: 1001:1001
    restart: unless-stopped

  sma:
    build: ./SMA_MODBUS_REQUESTER/
    restart: unless-stopped
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_ORGANISATION=
      - INFLUX_BUCKET=solar
      - INFLUX_TOKEN=
      - INTERVAL=15
      - DEBUG=1